// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Skill = Collections['skills']['schema']['_output']
export declare const skills: Skill[]
